//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMyCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_yetenek
    {
        public int yetenek_id_PK { get; set; }
        public string yetenek_adi { get; set; }
        public Nullable<byte> oran { get; set; }
    }
}
