//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMyCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_egitim
    {
        public int egitim_id_PK { get; set; }
        public string baslik { get; set; }
        public string alt_baslik { get; set; }
        public string alt_baslik_2 { get; set; }
        public string gnortalama { get; set; }
        public string tarih { get; set; }
    }
}
