//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMyCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hakkimda
    {
        public int hakkimda_id_PK { get; set; }
        public string isim { get; set; }
        public string soyisim { get; set; }
        public string adres { get; set; }
        public string telefon { get; set; }
        public string mail { get; set; }
        public string aciklama { get; set; }
        public string resim { get; set; }
    }
}
