//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMyCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hobi
    {
        public int hobi_id_PK { get; set; }
        public string aciklama_1 { get; set; }
        public string aciklama_2 { get; set; }
    }
}
